/* 英文值：顺序必须与 /tmp/zxtest/i18n-keys.json 的 htmlKeys 严格 1:1 对齐。
   由 build-i18n.js 与键合并生成 lang.en.js 的 html 词典。
   注意：值里的反斜杠要双写（\\Delta），标签与属性必须与键保持一致。 */
module.exports = [
`Skip to main content <span aria-hidden="true">↵</span>`,
`I am <strong>Zhaoqing Xu · 许钊箐</strong> — a Ph.D. candidate in Computational Mathematics in the Department of Mathematics at the University of South Carolina, advised by Prof. <strong>Xiaofeng Yang</strong>, and an Instructor of Record for undergraduate courses. By day I design energy-stable, structure-preserving schemes for <strong>phase-field models and interfacial dynamics</strong>; by night I write what lives outside the algorithm: essays, seven-character verse, and the aerodynamics hidden in a shuttlecock's flight. This page holds both halves — use <span class="kbd-inline">Mode</span> up top to switch lens and <span class="kbd-inline">中 / EN</span> to switch language. For the formal academic record see <a class="text-link" href="https://www.zhaoqingxu.com" target="_blank" rel="noopener">www.zhaoqingxu.com&nbsp;↗</a>.`,
`<a class="btn btn--pri" href="#research">Enter the research section <span aria-hidden="true">→</span></a> <a class="btn btn--ghost" href="#garden"><span aria-hidden="true">✦</span> Wander the idea garden</a> <a class="btn btn--quiet" href="#lab"><span aria-hidden="true">▶</span> Run a numerical experiment</a>`,
`Collaboration · Talks · Coffee`,
`<span>§ 01</span> / Research &amp; Math <em>— the rigorous half</em>`,
`Academic Space`,
`My work sits in <strong>computational and applied mathematics</strong> — designing efficient, <em class="ser-i">energy-stable</em> schemes for phase-field models and interfacial dynamics: the theory (unconditional stability, convergence analysis) as well as the algorithms (decoupled solvers, high-order IMEX methods, spectral collocation).`,
`<span aria-hidden="true">✓</span> The entries below mirror <a class="text-link" href="https://www.zhaoqingxu.com/research/" target="_blank" rel="noopener">zhaoqingxu.com/research&nbsp;↗</a>; the full CV is at <a class="text-link" href="https://www.zhaoqingxu.com/cv.pdf" target="_blank" rel="noopener">cv.pdf&nbsp;↗</a>. Code and preprints will be linked as they are released.`,
`<span class="philosophy__zh" lang="zh-Hans">教数学，是把严谨的论证变成可以看见、可以动手验证的东西。</span> Teaching mathematics is turning a rigorous argument into something you can see and verify with your own hands. Three principles: <strong>intuition first, rigor second</strong> (every theorem gets a picture before it gets a proof); <strong>computation as a lens</strong> (students run small numerical experiments and watch convergence happen); <strong>low floor, high ceiling</strong> (problems you can walk into, with room to stretch).`,
`<span class="honor__what"><b>Outstanding Student Award</b>, Summer School on Scientific Computing · Xiangtan University (group leader, second-place team)</span><span class="honor__when">2024</span>`,
`<a class="text-link" href="https://www.zhaoqingxu.com/research/" target="_blank" rel="noopener"> All papers, talks and courses on my academic site <span aria-hidden="true">↗</span> </a> <a class="text-link" href="https://www.zhaoqingxu.com/cv.pdf" target="_blank" rel="noopener"> Download CV (PDF) <span aria-hidden="true">↗</span> </a>`,
`<span>§ 01.b</span> / Math &amp; Method <em>— the beauty of discretization</em>`,
`Three discretization ideas I love most`,
`A good scheme is not simply "replace the derivative with a difference quotient" — it is about <strong>carrying the symmetries of the continuous world onto the grid</strong>. These three are the tools I work with every day. <span class="c-mute">Formulas are typeset by KaTeX; if the CDN is unreachable they fall back to monospace Unicode text.</span>`,
`Discrete Gradient <span class="method__cn">conservation by construction</span>`,
`<span class="method__key">the idea</span> Replace the gradient with the <em class="ser-i">average vector field</em> and the chain rule collapses into an algebraic identity. Then <span class="math" data-tex="H(u_{n+1})=H(u_n)">H(uₙ₊₁) = H(uₙ)</span> is not "approximately true" but <strong>exactly true at every step</strong> — no energy drift, even after a hundred thousand steps.`,
`Crank–Nicolson <span class="method__cn">mid-point implicit in time</span>`,
`<span class="method__key">the idea</span> Place the time derivative at the half-step mid-point, and symmetry buys you <strong>second-order accuracy plus A-stability</strong>: the step size is no longer strangled by <span class="math" data-tex="\\Delta t\\lesssim\\Delta x^{2}">Δt ≲ Δx²</span>. The price is one linear solve per step — usually a good trade.`,
`Scalar Auxiliary Variable <span class="method__cn">one scalar ODE tames the nonlinearity</span>`,
`<span class="method__key">the idea</span> The nonlinear term of a gradient flow is the nightmare of stability analysis. SAV hides the nonlinear energy inside <strong>a single scalar ODE</strong>, so the scheme at once becomes linear, second order, and dissipates a <em class="ser-i">modified energy</em> exactly. Phase-field models, liquid crystals and two-phase flow all lean on it.`,
`<span>§ 01.c</span> / Live experiment <em>— integrating a PDE in your browser</em>`,
`The CFL Stability Lab`,
`The one-dimensional linear advection equation <span class="math" data-tex="\\partial_t u + a\\,\\partial_x u = 0">∂ₜu + a·∂ₓu = 0</span> on a periodic domain, with a Gaussian wave-packet initial condition. Drag <span class="math" data-tex="\\Delta t">Δt</span> to change <span class="math" data-tex="\\nu=a\\,\\Delta t/\\Delta x">ν = aΔt/Δx</span> and watch the exact moment the CFL condition <span class="math" data-tex="|\\nu|\\le 1">|ν| ≤ 1</span> breaks. <span class="c-mute">Hand-written Canvas; no third-party library.</span>`,
`Your browser does not support canvas, so the numerical solution cannot be drawn here.`,
`Scheme`,
`Upwind (first order)`,
`Lax–Wendroff (second order)`,
`FTCS (centred, explicit — always blows up)`,
`<span class="method__key">why it is worth playing with</span> Upwind is monotone and stable for <span class="math" data-tex="0\\le\\nu\\le 1">0 ≤ ν ≤ 1</span>, but dissipative — the wave packet keeps flattening as it travels; Lax–Wendroff is second order and nearly non-dissipative, yet blows up exponentially once <span class="math" data-tex="\\nu>1">ν &gt; 1</span>; FTCS is unstable no matter what. That is the <strong>temperament of a scheme</strong>: accuracy, stability and monotonicity never all at once.`,
`<span>§ 02</span> / Essays &amp; Perspectives <em>— the living half</em>`,
`Essays &amp; Personal Views`,
`Beyond algorithms I also write cross-disciplinary notes, technical musings and some deliberately unsystematic philosophy. The two published pieces live under <a class="text-link" href="https://www.zhaoqingxu.com/notes/" target="_blank" rel="noopener">Musings · 漫谈&nbsp;↗</a> on my academic site; anything tagged <span class="essay__read">draft</span> is still being worked over — <em class="ser-i">if it deserves to be read, it deserves to be rewritten</em>.`,
`<a href="https://www.zhaoqingxu.com/notes/build-your-website-from-scratch/" target="_blank" rel="noopener">Build Your Personal Website from Scratch<span class="sr-only">(read the full post)</span></a>`,
`How to build your own academic / personal website from zero: the complete Hugo + AI workflow, <strong>no programming experience required</strong>. Domain, deployment, typography and every pitfall I hit — all in one post.`,
`#site-building`,
`<a href="https://www.zhaoqingxu.com/notes/hello-world/" target="_blank" rel="noopener">Hello, World — on launching this site<span class="sr-only">(read the full post)</span></a>`,
`Why I built this site, what I want to grow here, and a few notes on the design — <strong>the first post is addressed to my future self</strong>.`,
`#Chinese`,
`<time datetime="2026-06-14">2026.06.14</time> <span class="essay__read">draft · unpublished</span> <span class="essay__lens" data-lens-chip="">life</span>`,
`<a href="#" data-draft="">The interface is a worldview<span class="sr-only">(read the full post)</span></a>`,
`Whatever a piece of software puts above the fold is what it believes you should care about. Generalise it: <strong>your dashboard, your note structure, your calendar — each is a philosophical manifesto you quietly wrote for yourself.</strong>`,
`<time datetime="2026-04-27">2026.04.27</time> <span class="essay__read">draft · unpublished</span> <span class="essay__lens" data-lens-chip="">research</span>`,
`<a href="#" data-draft="">Why conservation matters more than accuracy<span class="sr-only">(read the full post)</span></a>`,
`A scheme with a smaller local truncation error that slowly leaks energy will hand you, after ten thousand periods, an orbit that simply does not exist in physics. That was the first life lesson numerical analysis taught me: <strong>long-term structural correctness beats short-term numerical prettiness.</strong>`,
`<time datetime="2025-12-09">2025.12.09</time> <span class="essay__read">draft · unpublished</span> <span class="essay__lens" data-lens-chip="">life</span>`,
`<a href="#" data-draft="">A digital-garden manifesto: why I stopped chasing "finished"<span class="sr-only">(read the full post)</span></a>`,
`A blog is a publication; a garden is a nursery. Allowing yourself to plant seeds that will never mature is what makes writing <strong>need no defence</strong> again.`,
`<span aria-hidden="true">◌</span> No essays in this lens. <button class="btn btn--quiet btn--sm" type="button" data-lens-reset="">Back to All</button>`,
`<span>§ 03</span> / Digital Garden &amp; Fragments <em>— slices of inspiration</em>`,
`Fragments, sticky notes and unfinished thoughts`,
`Unfiltered day-to-day records: one- or two-line excerpts, books and films and music, the aerodynamics of badminton, seven-character verse written at midnight, and ideas useful to nobody but me. <em class="ser-i">They will keep growing.</em>`,
`The elegance of a scheme is not in how small its error is,<br>but in how it <em class="ser-i">remembers what the continuous world forgot</em>.`,
`<span aria-hidden="true">🏸</span> notes on sports dynamics`,
`Badminton may be the only racket sport in which <strong>air drag runs everything</strong>: a smash can leave the strings above 300 km/h and arrive at under 30. I never tire of its equation —`,
`Drag grows with the square of speed and always points the other way, so the cork head flips itself forward — an attitude stabiliser that needs no control theory. Next time I play I want to measure that flipping time constant with a high-speed camera.`,
`<span aria-hidden="true">📜</span> seven-character verse · unfinished`,
`A thousand rows of grid points hold the sun and the moon`,
`One differencing step crosses the passes`,
`Energy does not scatter through the long night`,
`Inspiration springs up among the garbled bytes`,
`<span class="stamp">"Computing at Night"</span><time datetime="2026-09-02">09.02</time><span class="stage stage--seed">seed</span>`,
`Rereading chapter 3 of Gödel, Escher, Bach: "Recursion is not a trick; it is how the universe tells jokes." I filled an entire margin page, then closed the book and went for a long walk.`,
`<span aria-hidden="true">⌘</span> snippet · an eight-line symplectic integrator`,
`<code><span class="c-mute"># leapfrog (kick–drift–kick): symplectic, energy does not drift</span> <span class="c-key">def</span> <span class="c-fn">leapfrog</span>(q, p, dt, n, grad_V): <span class="c-key">for</span> _ <span class="c-key">in</span> range(n): p -= <span class="c-num">0.5</span> * dt * grad_V(q) <span class="c-mute"># half kick</span> q += dt * p <span class="c-mute"># full drift</span> p -= <span class="c-num">0.5</span> * dt * grad_V(q) <span class="c-mute"># half kick</span> <span class="c-key">return</span> q, p</code>`,
`Rewatching Blade Runner 2049. Conclusion: <strong>fog is a narrative device</strong> — it decides, on the director's behalf, how much the audience is allowed to know at this moment.`,
`The most fascinating thing about complex systems: <strong>stacking local optima tends to produce global absurdity.</strong> Reading an org chart always feels like reading a fable — and not unlike reading the stability analysis of a bad scheme.`,
`I marked 43 assignments this week, and the errors on problem 7 clustered tightly around a single symbol. The students are not lost — the textbook notation misled them. Next week I will first draw two pictures showing the difference between <span class="math" data-tex="\\partial u/\\partial t">∂u/∂t</span> and <span class="math" data-tex="\\mathrm{d}u/\\mathrm{d}t">du/dt</span>, and only then talk about schemes.`,
`Instructor of Record · teaching and learning feed each other`,
`The fixed soundtrack for late-night derivations: Glenn Gould's 1981 Goldberg Variations. Absurdly slow, yet exactly fast enough to keep up with my thinking — <strong>speed is the enemy of understanding; rhythm is its friend.</strong>`,
`Could the SAV idea be carried over to the time discretisation of neural ODEs, so that training itself strictly dissipates some "modified energy"? Noting it down here — I will touch it once this round of deadlines has passed.`,
`<span aria-hidden="true">🎼</span> lyrics · draft`,
`We slice the continuous world into cells,<br>and forget that between the cells there is wind too.<br>Error is not failure; it is the way the world <em class="ser-i">refuses to be fully described</em>.`,
`"The Discrete Wind" · chorus not final`,
`<span class="c-mute">The garden shows 12 fragments; another 40+ private drafts are slowly fermenting.</span>`,
`<span aria-hidden="true">◌</span> No fragments in this lens. <button class="btn btn--quiet btn--sm" type="button" data-lens-reset="">Back to All</button>`,
`<span>§ 04</span> / Side Projects &amp; Sandbox <em>— the digital workshop</em>`,
`Experimental code and small open toys`,
`Things I do not build for a KPI: numerical toys, AI experiments, visual tools and open-source fragments. Most of them are imperfect, and every one of them taught me something.`,
`<span aria-hidden="true">✓</span> The first four cards are <strong>genuinely live</strong> — the links open. Anything tagged <span class="pill pill--exp"><i></i>Concept</span> is still only an idea, not yet released.`,
`The lab in §01.c of this page: roughly 200 lines of vanilla JS + Canvas integrating the 1-D advection equation in real time — four schemes, adjustable Δt, drawing the CFL condition right in front of you.`,
`My academic site: Hugo with a customised PaperMod Ocean theme, bilingual (English / 中文), covering Research / Teaching / Musings / CV. The whole process — theme, domain, deployment — is written up as a tutorial.`,
`<a class="btn btn--sm" href="https://www.zhaoqingxu.com" target="_blank" rel="noopener">Visit <span aria-hidden="true">↗</span></a> <a class="btn btn--sm btn--outline" href="https://www.zhaoqingxu.com/notes/build-your-website-from-scratch/" target="_blank" rel="noopener">Build tutorial <span aria-hidden="true">↗</span></a>`,
`The page you are reading: a <strong>zero-dependency</strong> trio (HTML/CSS/JS) with a hand-written Canvas numerical lab, KaTeX formulas (Unicode fallback included), dual-lens filtering, a command palette and a 中 / EN switch. No build step, no trackers, no cookies.`,
`A small tool I keep imagining: compile a pile of Markdown fragments into a digital garden — backlinks, maturity stages and RSS in one pass. The note wall above is still hand-written for now.`,
`An experiment I want to run: feed Tang and Song poetry into a Markov chain and generate "modern verse". Probably my first serious encounter with randomness — and the first truce between mathematics and intuition. The code is not tidied up yet.`,
`The dark design tokens this site actually uses: colours, spacing, type scale and motion curves all expressed as CSS variables, with the accent colour field switching between the Research and Life lenses.`,
`<a class="text-link" href="https://github.com/PearsonXu?tab=repositories" target="_blank" rel="noopener"> See every repository on GitHub <span aria-hidden="true">↗</span> </a>`,
`<span aria-hidden="true">◌</span> No projects in this lens. <button class="btn btn--quiet btn--sm" type="button" data-lens-reset="">Back to All</button>`,
`<span>§ 05</span> / Contact <em>— let us talk about something</em>`,
`Write to me`,
`Collaboration, an invitation to give a talk, a disagreement about some scheme, or just a chat about badminton and aerodynamics — all welcome. My favourite kind of email is <em class="ser-i">"I read it, and I am not so sure I agree."</em>`,
`<a class="contact__mail" href="mailto:zhaoqing@email.sc.edu"> <span class="contact__label">email · UofSC</span> <span class="contact__addr">zhaoqing@email.sc.edu</span> </a> <button class="btn btn--ghost" type="button" data-copy="zhaoqing@email.sc.edu"> <span aria-hidden="true">⧉</span> Copy address </button>`,
`<span>Department of Mathematics · University of South Carolina</span> <span>2002 Greene St, Columbia, SC 29205</span> <span><a class="text-link" href="tel:+18034098998">+1 (803) 409-8998</a></span> <span>Secondary email <a class="text-link" href="mailto:806864070@qq.com">806864070@qq.com</a></span>`,
`<a class="matrix__link" href="https://www.zhaoqingxu.com/research/" target="_blank" rel="noopener"> <span class="matrix__key">Research</span> <span class="matrix__val">papers · manuscripts · talks</span> <span class="matrix__arrow" aria-hidden="true">↗</span> </a>`,
`<a class="matrix__link" href="https://www.zhaoqingxu.com/notes/" target="_blank" rel="noopener"> <span class="matrix__key">Musings · 漫谈</span> <span class="matrix__val">essays in English and Chinese</span> <span class="matrix__arrow" aria-hidden="true">↗</span> </a>`,
`<span class="math" data-tex="\\oint_{\\partial\\Omega}\\mathbf{F}\\cdot\\mathrm{d}\\mathbf{s}=\\iint_{\\Omega}\\left(\\nabla\\times\\mathbf{F}\\right)\\mathrm{d}A">∮∂Ω F·ds = ∬Ω (∇×F) dA</span> <span class="foot__sig-cap">— signed, Stokes</span>`,
`<a href="https://www.zhaoqingxu.com/notes/" target="_blank" rel="noopener">Musings ↗</a>`,
`<kbd>⌘</kbd><kbd>K</kbd> palette · <kbd>M</kbd> lens · <kbd>L</kbd> language · <kbd>↑</kbd> top`,
`Command palette`,
`<span><kbd>↑</kbd><kbd>↓</kbd> select</span> <span><kbd>↵</kbd> run</span> <span class="palette__hint">try <code>research</code> / <code>life</code> / <code>lab</code> / <code>mail</code> / <code>cv</code></span>`
];
